/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/16/2016
 */
package api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AuthenticationResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4994865703152187786L;
    private String accessToken;
    private String expiresIn;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("access_token")
    public String getAccessToken ( ) {
        return this.accessToken;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("access_token")
    public void setAccessToken (String value) {
        this.accessToken = value;
        notifyObservers(this.accessToken);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expires_in")
    public String getExpiresIn ( ) {
        return this.expiresIn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expires_in")
    public void setExpiresIn (String value) {
        this.expiresIn = value;
        notifyObservers(this.expiresIn);
    }
 
}
 