/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/16/2016
 */
package api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetAuthenticationInput 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5021892501063537938L;
    private String clientId;
    private String clientSecret;
    private String grantType = "client_credentials";
    private String scope = "SMS";
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("client_id")
    public String getClientId ( ) {
        return this.clientId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("client_id")
    public void setClientId (String value) {
        this.clientId = value;
        notifyObservers(this.clientId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("client_secret")
    public String getClientSecret ( ) {
        return this.clientSecret;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("client_secret")
    public void setClientSecret (String value) {
        this.clientSecret = value;
        notifyObservers(this.clientSecret);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("grant_type")
    public String getGrantType ( ) {
        return this.grantType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("grant_type")
    private void setGrantType (String value) {
        this.grantType = value;
        notifyObservers(this.grantType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("scope")
    public String getScope ( ) {
        return this.scope;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("scope")
    private void setScope (String value) {
        this.scope = value;
        notifyObservers(this.scope);
    }
 
}
 