/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/16/2016
 */
package api.models;
public enum ResponseStatusEnum {
    PEND, //The message is pending and has not yet been sent to the intended recipient
    SENT, //The message has been sent to the intended recipient, but has not been delivered yet
    DELIVRD, //The message has been delivered to the intended recipient
    READ; //The message has been read by intended recipient and the recipient's response has been received
    /**
    * Returns the enum member associated with the given integer value
    * @return	The enum member against the given integer value */
	@com.fasterxml.jackson.annotation.JsonCreator
	public static ResponseStatusEnum fromString(String toConvert) {
        return ResponseStatusEnum.valueOf(toConvert);
    }

	/**
    * Returns the integer value associated with the enum member
    * @return	The integer value against enum member */
	@com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return this.name();
    }
} 