/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/16/2016
 */
package com.telstra.api;
 
import android.content.Context;
import java.util.Date;
import com.android.volley.RequestQueue;
import com.android.volley.toolbox.Volley;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.telstra.com/v1";

    //retains status whether we have already initialized
    private static boolean initialized = false;
    private static RequestQueue requestQueue = null;

    //Initialization of configuration
    public static void initialize(Context context){
        if(initialized)
            return;
//            throw new IllegalStateException("Already initialized");
        requestQueue = Volley.newRequestQueue(context);
    
        initialized = true;
    }

	// volley request queue needs to be initialized before use
    public static RequestQueue getRequestQueue() {
        if(!initialized)
            throw new IllegalStateException("Must initialize before accessing request queue");
        return requestQueue;
    }

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "no need to config";

    public static String consumerKey = "ZDuzM5gKWl9IM8G4e0VMH2bKorRIU33t";
    public static String consumerSecret = "AUbyh8CJy8gASog1";
    public static Date tokenExpiry = new Date(0);

    public static String selfMobileNumber = "0413725868";

}
