/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/16/2016
 */
package com.telstra.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendMessageResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4614102338178650678L;
    private String messageId;
    /** GETTER
     * The unique id to identity the message sent. 
     */
    @JsonGetter("messageId")
    public String getMessageId ( ) {
        return this.messageId;
    }
    
    /** SETTER
     * The unique id to identity the message sent. 
     */
    @JsonSetter("messageId")
    public void setMessageId (String value) {
        this.messageId = value;
        notifyObservers(this.messageId);
    }
 
}
 